// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// User is the golang structure for table user.
type User struct {
	Id       int    `json:"id"       ` //
	Account  string `json:"account"  ` //
	Password string `json:"password" ` //
}
